name: "Pull Request"
description: Runs rules against PRs
inputs:
  ADMIN_PAT:
    description: ADMIN_PAT
    required: true
runs:
  using: composite
  steps:
    - name: PR Title Lint
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ inputs.ADMIN_PAT }}
